### ISSUE TITLE
Prints 

### ISSUE THREAD

**Issue by andersonvieiragomeslopes** [LHayate/Welic#27]
Olá, você tem imagens do aplicativo e do site para exibir? Me interessei pelo projeto.

**Comment by igormelo9001** [comment]
Cara esse projeto nao é meu. Mas posso te passar o contato da pessoa responsavel

**Comment by andersonvieiragomeslopes** [comment]
Obrigado.

Fico no aguardo @igormelo9001

**Comment by LHayate** [comment]
@andersonvieiragomeslopes Bom dia tudo bem ? 
Pode pegar o projeto sim contando que faça referencias corretamente ao criador do projeto se for utilizar para fins comerciais . 
Infelizmente não possuo mais os prints do projeto.  
Mas se poder aguarda, me dê umas 2 semanas que eu vou colocar ele no ar novamente e disponibilizo para você uma nova versão para testar. 
E caso queira dar opniões e melhorias para este projeto estaremos a disposição. 
Deixe-me saber quando pegar o projeto por favor! 


Meu skype para contato live:lucas.uzi

**Comment by andersonvieiragomeslopes** [comment]
> @andersonvieiragomeslopes Bom dia tudo bem ?
> Pode pegar o projeto sim contando que faça referencias corretamente ao criador do projeto se for utilizar para fins comerciais .
> Infelizmente não possuo mais os prints do projeto.
> Mas se poder aguarda, me dê umas 2 semanas que eu vou colocar ele no ar novamente e disponibilizo para você uma nova versão para testar.
> E caso queira dar opniões e melhorias para este projeto estaremos a disposição.
> Deixe-me saber quando pegar o projeto por favor!
> 
> Meu skype para contato live:lucas.uzi

Tudo bem, e você, @LHayate ?

Fico no aguardo, não tenho intenção de fazer uso comercial, vou entrar em contato via skype para colher maiores informações sobre o projeto.

Desde já eu lhe agradeço a atenção, até mais.
